#!/usr/bin/env bash

FILES=$(git status --porcelain | grep "^[AM]  .\+\.php$"  | grep -v ".\+\.blade\.php" | cut -d ' ' -f 3)

if [ "$FILES" ]; then
    docker compose exec --user=sesame -T app vendor/bin/pint $FILES

    STATUS=$?

    if [[ "$STATUS" -ne 0 ]]; then
        echo -e "\e[31mPHP-CS-Fixer failed\e[m"
        exit 1
    fi

    git add $FILES
fi
